config/routes.rb
AppAudit::Application.routes.draw do

  resources :details do
           get 'upgrade', :on => :collection
  end

  resources :warranties

  resources :jobs do
      get 'reportsjob', :on => :collection
      get 'reportsto', :on => :collection
  end

  resources :services

  resources :repairs

  resources :cars

  match '/car', :to => 'cars#index'

  root :to => 'cars#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :car
  has_one :repair
  has_one :service, through: :car
  has_many :details, through: :car
  attr_accessible :km_n, :m_ch, :repair_job, :to , :car_id  , :season_bool
  after_save :update_details_id
  before_update :edit_job
  with_options if: :km_n_and_m_ch? do |km|
    km.validates :km_n, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    km.validates :m_ch, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  end

  validates :car, presence: true
  validates_presence_of :repair_job, acceptance: true, :if => :repair_job
  validates_presence_of :to, acceptance: true, :if => :to
  validates_presence_of :season_bool, acceptance: true, :if => :season_bool
  def km_n_and_m_ch?
      if repair_job || to || season_bool
        return false
      else
        return true
      end
  end

  def edit_job
    Detail.where('details.car_id' => car_id ).each do |detail|
      detail.km_de_all -= detail.km_de_job
      detail.time_de_all -=  detail.time_de_job
      detail.save
    end
  end

  def update_details_id
    if to
      servic_up_param

    elsif season_bool
      servic_up_param
    end

    unless repair_job or to

    Car.where('cars.id' => car_id ).each do  |car|
      if car.ch_all.nil?
        car.ch_all = 0
      end
      if car.km_all.nil?
        car.km_all = 0
      end
      car.km_all += km_n
      car.ch_all += m_ch
      car.save

    end

    Detail.where('details.car_id' => car_id ).each do |detail|
     #p detail.job_id.nil?
     if detail.job_id.nil?
       detail.job_id = id
       if detail.time_de_all.nil?
         detail.time_de_all = 0
       end
       if detail.km_de_all.nil?
         detail.km_de_all = 0
       end

       detail.km_de_job = km_n
       detail.time_de_job = m_ch
       detail.time_de_all += detail.time_de_job
       detail.km_de_all += detail.km_de_job
       detail.save

     else


        detail.job_id = id
        if detail.time_de_all.nil?
          detail.time_de_all = 0
        end
        if detail.km_de_all.nil?
          detail.km_de_all = 0
        end

        detail.km_de_job = km_n
        detail.time_de_job = m_ch
        detail.time_de_all += detail.time_de_job
        detail.km_de_all += detail.km_de_job
        detail.save

      end
      end


    end


    #Car.joins("LEFT JOIN jobs ON cars.id = jobs.car_id").joins("LEFT JOIN details ON cars.id = details.car_id").where('details.car_id' =>inire)
  end

  private
  def servic_up_param

    if Service.where(car_id: car_id).empty?
      a= Service.new
      a.update_attributes( car_id: car_id, amount: 1, time_to: Time.new.strftime("%F"), season_sumer: Time.new(Time.new.year,04,19).strftime("%F") ,season_winter: Time.new(Time.new.year,10,19).strftime("%F")  )
      a.save
    else
      Service.where(car_id: car_id).each do |servic|
        servic.amount += 1
        servic.time_to = Time.new.strftime("%F")
        servic.save
      end

    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def reportsjob
    if params[:data_min] and params[:data_max]
      @jobs = Car.select("cars.name as name, Sum(jobs.km_n) as km_all , Sum(jobs.m_ch) as m_ch_all").joins(:jobs).where("date(jobs.created_at)>= ? AND date(jobs.created_at)<=?", params[:data_min], params[:data_max]).group("cars.name")
    else
      @jobs = Car.select("cars.name as name, Sum(jobs.km_n) as km_all , Sum(jobs.m_ch) as m_ch_all").joins(:jobs).group("cars.name")
     end
  end
  def reportsto


    if params[:data_min] and params[:data_max]
      @jobs_to = Car.select("cars.name,repairs.cause as causee, jobs.repair_job , details.name_det as name_detall, date(repairs.created_at) as date_repairs").where("date(jobs.created_at)>= ? AND date(jobs.created_at)<=?", params[:data_min], params[:data_max]).where( 'jobs.repair_job' => true ).joins(" INNER JOIN repairs ON repairs.car_id = cars.id INNER JOIN jobs ON repairs.job_id = jobs.id INNER JOIN details ON details.id = repairs.detail_id")
      @jobs_rep = Job.includes(:car).where("date(jobs.created_at)>= ? AND date(jobs.created_at)<=?", params[:data_min], params[:data_max]).where("'jobs'.'to' = ? or 'jobs'.'season_bool'= ?", true , true)

    else
      @jobs_to = Car.select("cars.name,repairs.cause as causee, repair_job , details.name_det as name_detall, date(repairs.created_at) as date_repairs").where( 'jobs.repair_job' => true ).joins(" INNER JOIN repairs ON repairs.car_id = cars.id INNER JOIN jobs ON repairs.job_id = jobs.id INNER JOIN details ON details.id = repairs.detail_id")
      @jobs_rep = Job.includes(:car).where("'jobs'.'to' = ? or 'jobs'.'season_bool'= ?", true , true)
    end

  end
  def index
    @jobs = Job.includes(:car).all

        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @jobs }
        end
      end

      # GET /jobs/1
      # GET /jobs/1.json
      def show
        @job =Job.find(params[:id])


        respond_to do |format|
          format.html # show.html.haml
          format.json { render json: @job }
        end
      end

      # GET /jobs/new
      # GET /jobs/new.json
      def new
        @job = Job.new

        respond_to do |format|
          format.html # new.html.haml
          format.json { render json: @job }
        end
      end

      # GET /jobs/1/edit
      def edit
        @job = Job.find(params[:id])
      end

      # POST /jobs
      # POST /jobs.json
      def create
        @job = Job.new(params[:job])


        respond_to do |format|
          if @job.save
            format.html { redirect_to @job, notice: 'Job was successfully created.' }
            format.json { render json: @job, status: :created, location: @job }

      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job) do |f|
  = f.error_notification

  .form-inputs
    = f.input :repair_job, label: 'На ремонте'
    = f.input :to, label: 'На ТО'
    = f.input :season_bool, label: 'Сезонное ТО'
    = f.input :car_id, collection: Car.order(:name) , label: 'Машина'
    = f.input :km_n
    = f.input :m_ch, collection: 1..24


  .form-actions
    = f.submit class: ["btn btn-primary"]

app/views/jobs/edit.html.erb
<h1>Редактирование работы</h1>

<%= render 'form' %>

<%= link_to 'Подробнее', @job, :class => "btn btn-success" %> |
<%= link_to 'Назад', jobs_path, :class => "btn" %>

app/views/jobs/index.html.erb
<h1>Список всех выполненных работ</h1>

<table class="table table-bordered">
  <tr>
    <th>Наименование машины</th>
    <th>На ремонте</th>
    <th>На тех. обслуживании</th>
    <th>Километров выполнено</th>
    <th>Мото-часов выполнено</th>
    <th>Дата создания</th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.car.name %></td>
    <td><%= job.repair_job ? 'да': 'нет' %> </td>
    <td><%= job.to ? 'да': 'нет'%></td>
    <td><%= job.km_n %></td>
    <td><%= job.m_ch %></td>
    <td><%= job.created_at.strftime("%Y-%m-%d ") %></td>
    <td><nobr><%= link_to 'Подробнее', job, :class => "btn btn-success btn-mini" %>
    <%= link_to 'Редактировать', edit_job_path(job), :class => "btn btn-info btn-mini" %>
    <%= link_to 'Удалить', job, method: :delete, data: { confirm: 'Вы уверены?' }, :class => "btn btn-danger btn-mini" %></nobr></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая работа', new_job_path, :class => "btn" %>

app/views/jobs/new.html.haml


= render 'form'



= link_to 'Back', jobs_path, :class => "btn"

app/views/jobs/reportsjob.html.erb
<h1>Отчет о работе за период</h1>
 <%= form_tag( reportsjob_jobs_path, :method => 'get') do %>
    <p>Выборка</p>
    <p>
     от  <%= text_field_tag 'data_min',value = nil, "data-behaviour"=>'datepicker'  %>
     до  <%= text_field_tag 'data_max',value = nil, "data-behaviour"=>'datepicker'  %>
    </p>
    <%= submit_tag "Выбрать", :name => nil, :class => "btn" %>
 <% end %>


<table class="table table-bordered">
  <tr>
    <th>Наименование</th>
    <th>Отработанные километры</th>
    <th>Отработанные часы</th>

  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.name %></td>
    <td><%= job.km_all %></td>
    <td><%= job.m_ch_all %></td>


  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая работа', new_job_path, :class => "btn" %>

app/views/jobs/reportsto.html.erb
<h1>Отчет о работе за период</h1>
 <%= form_tag( reportsto_jobs_path, :method => 'get') do %>
    <p>Выборка</p>
    <p>
     от  <%= text_field_tag 'data_min',value = nil, "data-behaviour"=>'datepicker'  %>
     до  <%= text_field_tag 'data_max',value = nil, "data-behaviour"=>'datepicker'  %>
    </p>
    <%= submit_tag "Выбрать", :name => nil, :class => "btn" %>
 <% end %>


<hr>
<p> Отчет о ремонтах и деталях </p>
<br />
<table class="table table-bordered">
  <tr>
    <th>Наименование машины </th>
    <th>Причина поломки</th>
    <th>Наименование детали </th>
    <th>Дата поломки</th>

  </tr>

<% @jobs_to.each do |job| %>
  <tr>
    <td><%= job.name%></td>
    <td><%= job.causee %></td>
    <td><%= job.name_detall %></td>
    <td><%= job.date_repairs %></td>

  


  </tr>
<% end %>
</table>
<hr>
<p> Отчет о техническом обслуживании </p>
<br />
<table class="table table-bordered">
  <tr>
    <th>Наименование машины</th>
    <th>Сезонное технического обслуживания </th>
    <th>Технического обслуживания</th>
    <th>Дата технического обслуживания</th>

  </tr>

  <% @jobs_rep.each do |job| %>
      <tr>
        <td><%= job.car.name%></td>
        <td><%= job.season_bool ? 'да' : 'нет' %></td>
        <td><%= job.to ? 'да' : 'нет' %></td>
        <td><%= job.created_at.strftime("%F") %></td>



      </tr>
  <% end %>
</table>

<%= link_to 'Новая работа', new_job_path, :class => "btn" %>

app/views/jobs/show.html.haml
-a= Service.where(car_id: @job.car_id)
-if(@job.repair_job)
  =link_to 'В ремонт', new_repair_url(car_id: @job.car_id, job_id: @job.id ), :class => "btn btn-success"
-elsif(@job.to)
  - a.each do |er|
    =link_to 'В техническое обслуживание', edit_service_path(er.id), :class => "btn btn-success "
-else
  .text
    Километров пройдено
    %p=@job.km_n
    Мото часов
    %p=@job.m_ch

= link_to 'Редактировать', edit_job_path(@job) , :class => "btn btn-info" unless @job.to or @job.repair
= link_to 'Назад', jobs_path, :class => "btn" unless @job.to or @job.repair