config/routes.rb
AppAudit::Application.routes.draw do

  resources :details do
           get 'upgrade', :on => :collection
  end

  resources :warranties

  resources :jobs do
      get 'reportsjob', :on => :collection
      get 'reportsto', :on => :collection
  end

  resources :services

  resources :repairs

  resources :cars

  match '/car', :to => 'cars#index'

  root :to => 'cars#index'

end

app/models/car.rb
# coding: UTF-8
class Car < ActiveRecord::Base
  belongs_to :warranty
  has_many :details, dependent: :destroy
  has_many :jobs , dependent: :destroy
  has_many :repairs, dependent: :destroy
  attr_accessible :date_of_commissioning, :date_warranty, :name, :object_subdivisiod, :warranty_id
  validates :object_subdivisiod, :name, length: {minimum: 2, maximum: 20}


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.includes(:warranty).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.haml
= simple_form_for(@car) do |f|
    = f.error_notification

    .form-inputs
        = f.input :name , label: 'Наименование'
        = f.input :object_subdivisiod , label: 'Объект подразделения'
        = f.input :date_of_commissioning , label: 'Дата ввода в эксплуатацию'
        = f.input :date_warranty , label: 'Дата гарантированного срока'
        = f.input :warranty_id, collection: Warranty.order(:name), label: 'Наименование страховой фирмы'



    .form-actions
    = f.submit class: ["btn btn-primary"]

app/views/cars/edit.html.erb
<h1>Редактирование машинки</h1>

<%= render 'form' %>

<%= link_to 'Подробнее', @car, :class => "btn btn-success" %> |
<%= link_to 'Назад', cars_path, :class => "btn" %>

app/views/cars/index.html.erb
<h1>Все машины</h1>

<table class="table table-bordered">
  <tr>
    <th>Наименование</th>
    <th>Объект подразделения</th>
    <th>Дата ввод в эксплуатацию</th>
    <th>Дата гарантированного срока</th>
    <th>Наименование страховой фирмы</th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.name %></td>
    <td><%= car.object_subdivisiod %></td>
    <td><%= car.date_of_commissioning %></td>
    <td><%= car.date_warranty %></td>
    <td><%= car.warranty_id.nil? ? "Нет страховки":car.warranty.name %></td>
    <td>
    <nobr>
    <%= link_to 'Подробнее', car, :class => "btn btn-success btn-mini" %>
    <%= link_to 'Редактировать', edit_car_path(car), :class => "btn btn-info btn-mini" %>
    <%= link_to 'Удалить', car, method: :delete, data: { confirm: 'Вы уверены?' }, :class => "btn btn-danger btn-mini" %>
    </nobr>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Создать новую машину', new_car_path, :class => "btn" %>

app/views/cars/new.html.erb
<h1>Создание новой машинки</h1>

<%= render 'form' %>

<%= link_to 'Назад', cars_path, :class => "btn"  %>

app/views/cars/show.html.erb
<h1>Подробнее</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Наименование объекта:</b>
  <%= @car.name %>
</p>

<p>
  <b>Объект подразделения:</b>
  <%= @car.object_subdivisiod %>
</p>

<p>
  <b>Дата ввода в эксплуатацию:</b>
  <%= @car.date_of_commissioning %>
</p>

<p>
  <b>Дата гарантированного обслуживания:</b>
  <%= @car.date_warranty %>
</p>

<p>
  <b>Наименование страховой:</b>
  <%= @car.warranty_id.nil? ? "Нет страховки":@car.warranty.name %>
</p>


<%= link_to 'Редактировать', edit_car_path(@car), :class => "btn btn-success" %> |
<%= link_to 'Назад', cars_path, :class => "btn" %>