config/routes.rb
AppAudit::Application.routes.draw do

  resources :details do
           get 'upgrade', :on => :collection
  end

  resources :warranties

  resources :jobs do
      get 'reportsjob', :on => :collection
      get 'reportsto', :on => :collection
  end

  resources :services

  resources :repairs

  resources :cars

  match '/car', :to => 'cars#index'

  root :to => 'cars#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_ancestry
  belongs_to :car
  has_many :repairs , dependent: :destroy
  belongs_to :warranty
  has_many :jobs, through: :car

  attr_accessible :name_det, :km_de_all, :km_de_job, :km_de_warranty, :time_de_all, :time_de_job, :time_de_warranty,:parent_id, :car_id, :warranty_id,:ancestry
  validates :car, presence: true
  validates :name_det, length: {minimum: 2, maximum: 20}
  validates :km_de_all, :km_de_job, :km_de_warranty,:time_de_all, :time_de_job, :time_de_warranty, numericality: {only_integer: true, greater_than_or_equal_to: 0}

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.includes(:car,:warranty).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end
  def upgrade
    @details = Detail.includes(:car,:warranty).all
    @tile = Car.all
    #Detail.all.each do |detail|
    #  @dem= detail.id
    #  @dem=update_attributes( :job_id => detail.jobs.last.id)
    #end

    respond_to do |format|
      format.html # upgrade.html.erb

    end


  end


  # GET /details/1
  # GET /details/1.json
  def show
    @detail = Detail.includes(:car).find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new(:parent_id => params[:parent_id])
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/details_helper.rb
module DetailsHelper
  def nested_details(details)
    details.map do |detail, sub_details|
      render(detail) + content_tag(:div, nested_details(sub_details), :class => "nested_details")
    end.join
  end
end

app/views/details/_form.html.haml
= simple_form_for(@detail) do |f|
    = f.error_notification

    .form-inputs
        = f.input :name_det , label: 'Наименование'
        = f.input :car_id, collection: Car.order(:name) , label: 'Машина'
        = f.input :warranty_id, collection: Warranty.order(:name), label: 'Страховка'
        = f.label "Подкласс"
        = f.grouped_collection_select(:parent_id, Car.order(:name), :details ,:name, :id , :name_det, prompt: true)
        = f.input :time_de_job, collection: 0..24 , label: 'Время работы'
        = f.input :time_de_all, label: 'Все время работы' , input_html: { value: '0' }
        = f.input :time_de_warranty , label: 'Время гарантии' , input_html: { value: '0' }
        = f.input :km_de_job, label: 'Отработано километров' , input_html: { value: '0' }
        = f.input :km_de_all, label: 'Общее количество километров' , input_html: { value: '0' }
        = f.input :km_de_warranty, label: 'Количество отработанных километров по гарантия' , input_html: { value: '0' }


    .form-actions
    = f.submit class: ["btn btn-primary"]

app/views/details/edit.html.erb
<h1>Редактирование детальки</h1>

<%= render 'form' %>

<%= link_to 'Подробнее', @detail, :class => "btn btn-success" %> |
<%= link_to 'Назад', details_path, :class => "btn" %>

app/views/details/index.html.erb
<h1>Список всех деталей</h1>

<table class="table table-bordered">
  <tr>
    <th>Наименование машины</th>
    <th>Наименование гарантии</th>
    <th>Наиминование детали</th>

    <!--<th>время работы</th>-->

    <th>Все время работы</th>
    <th>Время гарантии</th>
    <!--<th>отработано километров</th>-->
    <th>Общее количество километров</th>
    <th>Количество отработанных километров по гарантии</th>

    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.car.name %></td>
    <td><%= detail.warranty_id.nil? ? "Нет страховки":detail.warranty.name %></td>
    <td><%= detail.name_det %></td>
    <td><%= detail.time_de_all %></td >
    <!--<td><%= detail.time_de_all %></td>-->
    <td><%= detail.time_de_warranty %></td>
    <!--<td><%= detail.km_de_job %></td>-->
    <td><%= detail.km_de_all %></td>
    <td><%= detail.km_de_warranty %></td>

    <td><nobr><%= link_to 'Подробнее', detail, :class => "btn btn-success btn-mini" %>
    <%= link_to 'Редактировать', edit_detail_path(detail), :class => "btn btn-info btn-mini" %>
    <%= link_to 'Удалить', detail, method: :delete, :class => "btn btn-danger btn-mini" %></nobr></td>
    <!--<td><%= link_to 'в ремонт', new_repair_url(detail_id: detail.id, car_id: detail.car_id  ) %></td>-->



  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая деталь', new_detail_path, :class => "btn" %>

app/views/details/new.html.erb
<h1>Новая деталька</h1>

<%= render 'form' %>


<%= link_to 'Назад', details_path, :class => "btn" %>

app/views/details/show.html.erb

<p id="notice"><%= notice %></p>

<p>
  <b>Наиминование машины:</b>
  <%= @detail.car.name %>
</p>

<p>
  <b>Страховая фирма:</b>
  <%= @detail.warranty_id.nil? ? "Нет страховки":@detail.warranty.name %>
</p>

<p>
  <b>Время работы:</b>
  <%= @detail.time_de_job %>
</p>

<p>
  <b>Все время работы:</b>
  <%= @detail.time_de_all %>
</p>

<p>
  <b>Время гарантии:</b>
  <%= @detail.time_de_warranty %>
</p>

<p>
  <b>Отработано километров:</b>
  <%= @detail.km_de_job %>
</p>

<p>
  <b>Общее количество километров:</b>
  <%= @detail.km_de_all %>
</p>

<p>
  <b>Количество отработанных километров по гарантия:</b>
  <%= @detail.km_de_warranty %>
</p>


<%= link_to 'Редактировать', edit_detail_path(@detail), :class => "btn btn-info" %> |
<%= link_to 'Назад', details_path, :class => "btn" %>

app/views/details/upgrade.erb
<h1>Список деталей</h1>

<table class="table table-bordered">
  <tr>
    <th>Машинка</th>
    <th>Страховая компания</th>
    <th>Наиминование</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @details.each do |detail| %>




      <tr>
        <td><%= detail.jod_id%></td>
        <td><%= detail.jobs.last.id %></td>


      </tr>
  <% end %>
</table>

<br/>
<div class="form-actions">
  <button type="submit" class="btn btn-primary">Сохранить</button>
  <button type="button" class="btn">Отменить</button>
</div>

