config/routes.rb
AppAudit::Application.routes.draw do

  resources :details do
           get 'upgrade', :on => :collection
  end

  resources :warranties

  resources :jobs do
      get 'reportsjob', :on => :collection
      get 'reportsto', :on => :collection
  end

  resources :services

  resources :repairs

  resources :cars

  match '/car', :to => 'cars#index'

  root :to => 'cars#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Предложение аудита</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <ul class="well nav nav-pills nav-stacked">
        <li class="nav-header">ГЛАВНОЕ МЕНЮ</li>
        <li class="<%='active' if current_page?(:controller => "cars") %>"><%= link_to "Машины", cars_path() %></li>
        <li class="<%='active' if current_page?(:controller => "warranties") %>"><%= link_to "Страховка", warranties_path() %></li>
        <li class="<%='active' if current_page?(:controller => "details") %>"><%= link_to "Детали", details_path() %></li>
        <li class="<%='active' if current_page?(:controller => "jobs") %>"><%= link_to "Отработка", jobs_path() %></li>
        <li class="<%='active' if current_page?(:controller => "repairs") %>"><%= link_to "Ремонт", repairs_path() %></li>
        <li class="<%='active' if current_page?(:controller => "services") %>"><%= link_to "Тех. обслуживание", services_path() %></li>
        <li class="<%='active' if current_page?(:controller => "jobs", action: "reportsto") %>"><%= link_to "Отчет ТО", reportsto_jobs_path() %></li>
        <li class="<%='active' if current_page?(:controller => "jobs", action: "reportsjob") %>"><%= link_to "Отчет работы", reportsjob_jobs_path() %></li>

      </ul>
    </div>
    <div class="span10">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>